# Generated by Django 4.1.3 on 2022-11-30 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planteamientos',
            name='on_act',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.acta', verbose_name='Planteamiento en Acta:'),
        ),
    ]
