# Generated by Django 4.1.3 on 2022-11-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_planteamientos_planteamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planteamiento',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='planteamiento',
            name='name',
        ),
    ]
