# Generated by Django 4.1.3 on 2022-11-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_planteamiento_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='lasname',
            new_name='lastname',
        ),
    ]
