# Generated by Django 4.1.3 on 2023-01-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_acta_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='cuota',
            field=models.FloatField(null=True, verbose_name='Introduza la Cuota Mensual '),
        ),
        migrations.DeleteModel(
            name='Planteamiento',
        ),
    ]
