# Generated by Django 4.1.3 on 2023-01-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_worker_cuota_delete_planteamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='description',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
