# Generated by Django 4.1.3 on 2023-01-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_acta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='description',
            field=models.TextField(max_length=20000, null=True),
        ),
    ]
